### ISSUE TITLE
Cannot split JPEGs

### ISSUE THREAD

**Issue by pathawks** [nrpatel/lfptools#3]
When I split a *-stk.lfp file, I do not get any JPEGs. Only the following files.
- `IMG_0030-stk_table.json`
- `IMG_0030-stk_imageRef0.raw`
- `IMG_0030-stk_blockOfImagesRef0.json`
- `IMG_0030-stk_blockOfImagesRef1.json`

Did Lytro change something?

**Comment by behnam** [comment]
Yes, so much has changed in stk.lfp files since Lytro Desktop version 2.0, and here are no JPEG data stored in the files anymore.

**Comment by nrpatel** [comment]
With eweidaw's change, the 2.0 files can be split properly.
