### ISSUE TITLE
Will this project be continued?

### ISSUE THREAD

**Issue by netsi1964** [nrpatel/lfptools#5]
Hi,
I just bought a Lytro camera, being a front end web developer I would love to see an API for the Lytro web files. For instance events data on the onclick event with say distance of the point clicked, which jpeg to use and so on. Also a method which would allow for setFocus(distance)

Are you guys aware of any official support from Lytro? Oh, and a precompiled version of your tool (for Mac OSX Mountain Lion) would be appreciated! :-)

/Sten

**Comment by nrpatel** [comment]
Most likely not.  I don't have time to continue working on it.

**Comment by behnam** [comment]
Sten, I'm interesting in developing a comprehensive C library for LFP files, and maybe in a year get to the processing algorithms. Let me know if you're interested too.

**Comment by netsi1964** [comment]
@behnam I am interested, I see the nature of Lytro camera being perfect for open souce software apps. I can however not help with any C programming :-) Javascript, HTML, CSS is my game :-)
